version: "3.9"

services:
  backend:
    build:
      context: ./sbrn-backend 
      dockerfile: dockerfile 
    container_name: SBRN 
    ports: 
      - 3000:3000
    env_file: 
      - ./sbrn-backend/.env 
    volumes: 
      - ./sbrn-backend:/app 
      - /app/node_modules 
      - /app/node_modules/.prisma
    restart: unless-stopped
    networks:
      - app-network 

  frontend:
    build: 
      context: .
      dockerfile: dockerfile
    container_name: RN 
    ports:
      - 5173:5173
    volumes:
      - .:/app                  # ðŸ‘ˆ Add for hot reload
      - /app/node_modules       # ðŸ‘ˆ Preserve node_modules
    depends_on: 
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge